name: Mi Primer Workflow
on: [workflow_dispatch]
jobs:
  saludar:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [self-hosted,ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - run: echo "Â¡Hola Mundo!"